"""test 2

Revision ID: 04325cc2d38c
Revises: 94a5fc93b3d7
Create Date: 2021-10-31 15:15:40.266975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04325cc2d38c'
down_revision = '94a5fc93b3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TradingHistory',
    sa.Column('smartContractAddress', sa.String(length=255), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('timeStamp', sa.DateTime(timezone=6), nullable=False),
    sa.Column('eventType', sa.String(length=255), nullable=False),
    sa.Column('salePrice', sa.Float(), nullable=True),
    sa.Column('saleCurrency', sa.String(length=255), nullable=True),
    sa.Column('usdSalePrice', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['smartContractAddress'], ['SmartContract.smartContractAddress'], ),
    sa.PrimaryKeyConstraint('smartContractAddress', 'token_id', 'timeStamp', 'eventType')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TradingHistory')
    # ### end Alembic commands ###
