"""test 3

Revision ID: 2dff9dcf3dd4
Revises: 96a0b63b2850
Create Date: 2021-10-31 15:31:25.643305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2dff9dcf3dd4'
down_revision = '96a0b63b2850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SmartContract', sa.Column('assetDescription', sa.TEXT(), nullable=True))
    op.drop_column('SmartContract', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SmartContract', sa.Column('description', mysql.TEXT(), nullable=True))
    op.drop_column('SmartContract', 'assetDescription')
    # ### end Alembic commands ###
