"""test 2

Revision ID: 4ad5c1cc9c60
Revises: 04325cc2d38c
Create Date: 2021-10-31 15:18:53.195206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad5c1cc9c60'
down_revision = '04325cc2d38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TradingHistory',
    sa.Column('smartContractAddress', sa.String(length=255), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('timeStamp', sa.DateTime(timezone=6), nullable=False),
    sa.Column('eventType', sa.String(length=255), nullable=False),
    sa.Column('salePrice', sa.Float(), nullable=True),
    sa.Column('saleCurrency', sa.String(length=255), nullable=True),
    sa.Column('usdSalePrice', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['smartContractAddress'], ['SmartContract.smartContractAddress'], ),
    sa.PrimaryKeyConstraint('smartContractAddress', 'token_id', 'timeStamp', 'eventType')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TradingHistory')
    # ### end Alembic commands ###
