"""test 2

Revision ID: 94a5fc93b3d7
Revises: 3b586e8e69e5
Create Date: 2021-10-31 15:15:13.824664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94a5fc93b3d7'
down_revision = '3b586e8e69e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TradingHistory')
    op.add_column('SmartContract', sa.Column('safeListRequestStatus', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SmartContract', 'safeListRequestStatus')
    op.create_table('TradingHistory',
    sa.Column('smartContractAddress', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('token_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timeStamp', mysql.DATETIME(), nullable=False),
    sa.Column('eventType', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('salePrice', mysql.FLOAT(), nullable=True),
    sa.Column('saleCurrency', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('usdSalePrice', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['smartContractAddress'], ['SmartContract.smartContractAddress'], name='TradingHistory_ibfk_1'),
    sa.PrimaryKeyConstraint('smartContractAddress', 'token_id', 'timeStamp', 'eventType'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
