"""test 2

Revision ID: 96a0b63b2850
Revises: 4019005a5d4d
Create Date: 2021-10-31 15:30:44.752804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96a0b63b2850'
down_revision = '4019005a5d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SmartContract', sa.Column('assetName', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('SmartContract', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SmartContract', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('SmartContract', 'assetName')
    # ### end Alembic commands ###
